// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action returns an integer. It uses Java "indexOf" method.
 * 
 * First object in the list is positions at index "0".
 * If there is no object in the list, it will return "-1".
 * If list is empty, it will return "-1".
 * If object is "Empty", it will throw an error.
 */
public class JA_List_GetIndexOfObject extends UserAction<java.lang.Long>
{
	private final java.util.List<IMendixObject> ProvidedList;
	private final IMendixObject ObjectToLookFor;

	public JA_List_GetIndexOfObject(
		IContext context,
		java.util.List<IMendixObject> _providedList,
		IMendixObject _objectToLookFor
	)
	{
		super(context);
		this.ProvidedList = _providedList;
		this.ObjectToLookFor = _objectToLookFor;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE

		if (ObjectToLookFor == null) {
		    throw new IllegalArgumentException("ObjectToLookFor parameter should be a valid object of the same type as the provided list");
		}

		if (ProvidedList == null || ProvidedList.isEmpty()) {
		    return (long) -1;
		}

		return (long) ProvidedList.indexOf(ObjectToLookFor);
	
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_List_GetIndexOfObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
