// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import java.util.ArrayList;
import java.util.stream.Collectors;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This Java action filters provided list using "isChanged" method on objects from Provided list.
 * If object was changed, it will be returned within the new list.
 * Commits it if requested through "Commit" parameter.
 * Returns a new filtered list.
 */
public class JA_List_FilterChanged extends UserAction<java.util.List<IMendixObject>>
{
	private final java.util.List<IMendixObject> ProvidedList;
	private final java.lang.Boolean Commit;

	public JA_List_FilterChanged(
		IContext context,
		java.util.List<IMendixObject> _providedList,
		java.lang.Boolean _commit
	)
	{
		super(context);
		this.ProvidedList = _providedList;
		this.Commit = _commit;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		if (ProvidedList == null || ProvidedList.isEmpty()) {
			// We return empty list in case if empty list was provided on TopLevel
			return new ArrayList<IMendixObject>();
		}
		
		java.util.List<IMendixObject> resultList = this.ProvidedList
				.stream()
				.filter(IMendixObject::isChanged)
		        .collect(Collectors.toList());
		
		// Commit filtered objects if "Commit" is set to true
		if (Commit) {
			Core.commit(getContext(), resultList);
		}
		
		return resultList;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_List_FilterChanged";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
