// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import java.util.Random;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * This java action returns an object randomly picked from the Provided list of objects.
 * Returns empty object if the list is empty
 * Uses java.util.Random class to randomize
 */
public class JA_List_GetRandomObject extends CustomJavaAction<IMendixObject>
{
	private java.util.List<IMendixObject> ProvidedList;

	public JA_List_GetRandomObject(IContext context, java.util.List<IMendixObject> ProvidedList)
	{
		super(context);
		this.ProvidedList = ProvidedList;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		// We return empty object if provided list does not contain at least one object
		if (ProvidedList == null || ProvidedList.isEmpty()) {
	        return null;
	    }
		
		// https://stackoverflow.com/questions/12487592/randomly-select-an-item-from-a-list
		Random randomizer = new Random();
		return ProvidedList.get(randomizer.nextInt(ProvidedList.size()));
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_List_GetRandomObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
