// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import objectlistoperations.impl.Sorting;
import objectlistoperations.impl.SortingValidation;
import objectlistoperations.impl.SortingValidation.ValidationFeedback;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action takes a list of objects and 'santizes' their data for sorting. All logic is applied to the input attribute. which should be used to determine the sorting order.
 * The objects are ordered based on any exisiting values (nulls are placed at the end of the list). Then, the value of SortOrderAttribute is set to value of "Starting index" parameter for the first object, +1 for the second, etc..
 * The result is a clean set of values for the list, meaning they are now in a format which can be used by the other sorting actions.
 * Commits changed objects if "Commit" parameter set to "true".
 * Returns changed objects if any in a new list otherwise returns empty list.
 */
public class JA_List_SanitizeSorting extends UserAction<java.util.List<IMendixObject>>
{
	private final java.util.List<IMendixObject> ProvidedList;
	private final java.lang.String SortAttributeName;
	private final java.lang.Boolean Commit;
	private final java.lang.Long StartingIndex;

	public JA_List_SanitizeSorting(
		IContext context,
		java.util.List<IMendixObject> _providedList,
		java.lang.String _sortAttributeName,
		java.lang.Boolean _commit,
		java.lang.Long _startingIndex
	)
	{
		super(context);
		this.ProvidedList = _providedList;
		this.SortAttributeName = _sortAttributeName;
		this.Commit = _commit;
		this.StartingIndex = _startingIndex;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		
		ValidationFeedback Validation = SortingValidation.performSanitizingValidation(ProvidedList, context, SortAttributeName, Commit, StartingIndex);
		if (!Validation.Valid) {
			throw new Exception(Validation.ValidationMessage);
		}
		
		List<IMendixObject> resultList = Sorting.listSanitize(ProvidedList, context, SortAttributeName, Commit, StartingIndex);
		
		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_List_SanitizeSorting";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
