// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import objectlistoperations.impl.Sorting;
import objectlistoperations.impl.SortingValidation;
import objectlistoperations.impl.SortingValidation.ValidationFeedback;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This Java action takes an object and a list (which the object is also part of) and changes that object's sort order attribute in the list to the specified number.
 * Commits changed objects if "Commit" parameter set to "true".
 * Returns changed objects if any in a new list otherwise returns empty list.
 */
public class JA_List_MoveObjectToPosition extends UserAction<java.util.List<IMendixObject>>
{
	private final IMendixObject ObjectToChange;
	private final java.util.List<IMendixObject> ProvidedList;
	private final java.lang.String SortAttributeName;
	private final java.lang.Long NewPosition;
	private final java.lang.Boolean Commit;

	public JA_List_MoveObjectToPosition(
		IContext context,
		IMendixObject _objectToChange,
		java.util.List<IMendixObject> _providedList,
		java.lang.String _sortAttributeName,
		java.lang.Long _newPosition,
		java.lang.Boolean _commit
	)
	{
		super(context);
		this.ObjectToChange = _objectToChange;
		this.ProvidedList = _providedList;
		this.SortAttributeName = _sortAttributeName;
		this.NewPosition = _newPosition;
		this.Commit = _commit;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
				
		ValidationFeedback Validation = SortingValidation.performPositionValidation(ProvidedList, ObjectToChange, context, SortAttributeName, NewPosition, Commit);
		if (!Validation.Valid) {
			throw new Exception(Validation.ValidationMessage);		
		}
		
		List<IMendixObject> resultList = Sorting.moveToPosition(ProvidedList, ObjectToChange, context, SortAttributeName, NewPosition, Commit, Validation.MxPrimitiveType);
		
		return resultList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_List_MoveObjectToPosition";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
