// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package objectlistoperations.actions;

import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import objectlistoperations.impl.Sorting_V1;
import objectlistoperations.impl.SortingValidation_V1;
import objectlistoperations.impl.SortingValidation_V1.ValidationFeedback;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action takes a list of objects and 'santizes' their data for sorting. All logic is applied to the input attribute. which should be used to determine the sorting order.
 * The objects are ordered based on any exisiting values (nulls are placed at the end of the list). Then, the value of SortOrderAttribute is set to 1 for the first object, 2 for the second, etc..
 * The result is a clean set of values for the list, meaning they are now in a format which can be used by the other sorting actions.
 * 
 * Deprecated. Please use JA_List_SanitizeSorting instead
 */
public class JA_SanitizeList extends UserAction<java.lang.Void>
{
	private final java.util.List<IMendixObject> ListToSanitize;
	private final java.lang.String SortAttributeName;
	private final java.lang.Boolean Commit;

	public JA_SanitizeList(
		IContext context,
		java.util.List<IMendixObject> _listToSanitize,
		java.lang.String _sortAttributeName,
		java.lang.Boolean _commit
	)
	{
		super(context);
		this.ListToSanitize = _listToSanitize;
		this.SortAttributeName = _sortAttributeName;
		this.Commit = _commit;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		
		// Set variables
		IContext context = this.getContext();
		List<IMendixObject> ListToSanitize = this.ListToSanitize;
		String SortAttributeName = this.SortAttributeName;
		Boolean Commit = this.Commit;
		
		ValidationFeedback Valid = SortingValidation_V1.performSanitizingValidation(ListToSanitize, context, SortAttributeName, Commit);
		
		
		if (Valid.Valid == true) {
		Sorting_V1.listSanitize(ListToSanitize, context, SortAttributeName, Commit);
		
		} else {
			throw new Exception(Valid.ValidationMessage);
		}
		
		return null;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_SanitizeList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
